### PR TITLE
Fixes Issue#16 : Dockerized the Project and Updated the README.md

### LINKED ISSUE #16: Dockerize the whole setup
### Description
 Currently, the setup consists of npm dependencies and mongodb to run the whole setup. MongoDB is required to download and setup separately. Dockerizing the whole setup will make it easier to focus on the development part and less on setting up.

Requirements:
- [ ] Create a Dockerfile to install npm dependencies and run the API
- [ ] Create a Dockerfile to setup MongoDB
- [ ] Create a docker-compose file to run both of those simultaneously

### PR DESCRIPTION
**Pull request by jain-rishabh-21**
# Related Issue
- closes #16: Dockerize the whole setup

# Proposed Changes
- Dockerized the app by adding 2 files i.e Dockerfile and docker-compose.yml 
- Updated the Docs

# Additional Info
- NA

# Checklist
- [x] Tests
- [x] Translations
- [x] Documentation

# Screenshots
NA
Original                |  Updated
:---------------------------:|:--------------------------:
** original screenshot ** | ** updated screenshot **

### CODE REVIEW

**Comment by ShauryaAg** [comment]
Please include environment variables for the `mongo` image to specify `MONGO_INITDB_DATABASE`, `MONGO_INITDB_ROOT_USERNAME`, `MONGO_INITDB_ROOT_PASSWORD`, and change the `.env` file to point to that database, instead of having it as `<DATABASE-NAME>`.

**Comment by ShauryaAg** [comment]
You may use [this](https://hub.docker.com/_/mongo) and [this](https://stackoverflow.com/questions/42912755/how-to-create-a-db-for-mongodb-container-on-start-up) for reference.

**Comment by ShauryaAg** [comment]
Please define some default values for `MONGO_INITDB_DATABASE`, `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD` (such as `admin`, `password`, `REST-fetch-db`) in the `.env` file, as our goal with this docker setup is to minimize the setup process.

File: src/app.ts [hunk 1]
```diff
@@ -9,9 +9,18 @@ const homeRoute = require('./api/routes/home')
...
+  useFindAndModify: false,
+};
 // Connect to database
-mongoose.connect(`${process.env.DB_CONNECTION_URL}`,
-    { useUnifiedTopology: true, useNewUrlParser: true })
+const url = `mongodb://${process.env.MONGO_NON_ROOT_USERNAME}:` + `${process.env.MONGO_NON_ROOT_PASSWORD}` + `@` + `mongodb:27017` + `/${process.env.MONGO_INITDB_DATABASE}`
+
+mongoose.connect(url, options)
+console.log(url)
+console.log("Connected")
```
Comment (ShauryaAg) [inline src/app.ts:22]: `mongoose.connect()` returns a Promise, please have the `console.log("Connected")` as a callback function.
Put `console.log()`, as `.then(() => {..})` after `mongoose.connect()`

File: src/app.ts [hunk 2]
```diff
@@ -9,9 +9,18 @@ const homeRoute = require('./api/routes/home')
...
 
+const options = {
+  useNewUrlParser: true,
+  useCreateIndex: true,
+  useFindAndModify: false,
+};
 // Connect to database
-mongoose.connect(`${process.env.DB_CONNECTION_URL}`,
-    { useUnifiedTopology: true, useNewUrlParser: true })
+const url = `mongodb://${process.env.MONGO_NON_ROOT_USERNAME}:` + `${process.env.MONGO_NON_ROOT_PASSWORD}` + `@` + `mongodb:27017` + `/${process.env.MONGO_INITDB_DATABASE}`
```
Comment (ShauryaAg) [inline src/app.ts:18]: The point of using formatted strings (`` `${var}-someString` ``) is so that we don't have to concatenate strings. Please use formatted strings correctly.

**Review by ShauryaAg — CHANGES_REQUESTED** [review]

File: src/app.ts (hunk 1 above)
Comment (jain-rishabh-21) [reply src/app.ts:22]: I just used it for development purpose, Should I keep it or remove it!

File: src/app.ts (hunk 2 above)
Comment (jain-rishabh-21) [reply src/app.ts:18]: Yup got it!

File: src/app.ts [hunk 3]
```diff
@@ -9,9 +9,18 @@ const homeRoute = require('./api/routes/home')
...
+};
 // Connect to database
-mongoose.connect(`${process.env.DB_CONNECTION_URL}`,
-    { useUnifiedTopology: true, useNewUrlParser: true })
+const url = `mongodb://${process.env.MONGO_NON_ROOT_USERNAME}:${process.env.MONGO_NON_ROOT_PASSWORD}@mongodb:27017/${process.env.MONGO_INITDB_DATABASE}`
+
+mongoose.connect(url, options).then(() => {
+    console.log("Connected")
+})
+console.log(url)
```
Comment (ShauryaAg) [inline src/app.ts:23]: Please remove this line.

**Review by ShauryaAg — CHANGES_REQUESTED** [review]

**Review by ShauryaAg — APPROVED** [review]

File: README.md [hunk 4]
```diff
@@ -13,10 +13,11 @@ The project is live [here](https://rest-fetch.herokuapp.com/)
 ## Installation
 Follow the instructions to get started with the project on your local machine 🚀
 * Fork and clone the project
-* `cd fetch/` and run `npm install` to install dependencies
```
Comment (adityabisoi) [inline README.md:16]: We should not remove the non-docker method completely. Instead, write a separate section in README for the Docker setup.

File: src/app.ts [hunk 5]
```diff
@@ -9,9 +9,17 @@ const homeRoute = require('./api/routes/home')
...
 
+const options = {
+  useNewUrlParser: true,
+  useCreateIndex: true,
+  useFindAndModify: false,
+};
 // Connect to database
-mongoose.connect(`${process.env.DB_CONNECTION_URL}`,
-    { useUnifiedTopology: true, useNewUrlParser: true })
+const url = `mongodb://${process.env.MONGO_NON_ROOT_USERNAME}:${process.env.MONGO_NON_ROOT_PASSWORD}@mongodb:27017/${process.env.MONGO_INITDB_DATABASE}`
```
Comment (adityabisoi) [inline src/app.ts:18]: We should find a way to adjust the `url` such that both the docker and non-docker options can be used.

File: README.md (hunk 4 above)
Comment (jain-rishabh-21) [reply README.md:16]: Okay, will see this
